# Generated by Django 4.0.4 on 2022-05-31 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=40)),
                ('desc_full', models.CharField(max_length=100)),
                ('price', models.FloatField()),
            ],
        ),
    ]
