# Generated by Django 4.0.4 on 2022-06-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0005_product_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc_full',
            field=models.TextField(),
        ),
    ]
