# Generated by Django 4.0.4 on 2022-06-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0006_alter_product_desc_alter_product_desc_full'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='picture',
            new_name='picture1_url',
        ),
        migrations.AddField(
            model_name='product',
            name='picture2_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='picture3_url',
            field=models.URLField(default=''),
        ),
    ]
