# Generated by Django 4.0.4 on 2022-06-03 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0009_rename_price_product_price_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='store_app.currency'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_USD',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
