# Generated by Django 4.0.4 on 2022-06-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0010_product_currency_alter_product_price_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.CharField(max_length=200),
        ),
    ]
